import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRecoilValue } from "recoil";
import { modalState } from "../atoms/modalAtom";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Modal from "../components/Modal";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";
import brand from "../images/Mygram.png";
import DummySidebar from "../components/DummySidebar";
import BottomNav from "../components/BottomNav";

export default function Home() {
  const { data: session } = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Mygram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* HEADER WHEN THE USER IS NOT LOGGED IN */}
      {!session && (
        <div className="hidden items-center justify-center mt-5 md:flex">
          <Image src={brand} width={200} alt="brand-pic" />
        </div>
      )}
      {/* HEADER SECTION FOR MOBILE VIEW */}
      <div className="md:hidden block">
        <Header />
      </div>
      <div className="flex items-start">
        {session ? (
          <div className="hidden md:block">
            {" "}
            <Sidebar />
          </div>
        ) : (
          <div className="hidden md:block">
            {" "}
            <DummySidebar />
          </div>
        )}
        {/* FEED */}
        <div className="flex items-center justify-center">
          <Feed />
        </div>{" "}
      </div>
      {/* MODAL SECTION */}
      <Modal />
      <BottomNav />
    </div>
  );
}
